export const BaseColor = {
    primary: '#5DADE2',
    primaryDark: '#1281ac',
    primaryLight: '#68c9ef',
    accent: '#FF8A65',
    background: 'white',
    card: '#F5F5F5',
    text: '#212121',
    border: '#c7c7cc',
    grayColor: '#9B9B9B',
    dividerColor: '#BDBDBD',
    whiteColor: '#FFFFFF',
    fieldColor: '#F5F5F5',
    yellowColor: '#FDC60A',
    navyBlue: '#3C5A99',
    kashmir: '#5D6D7E',
    orangeColor: '#E5634D',
    blueColor: '#5DADE2',
    pinkColor: '#A569BD',
    greenColor: '#58D68D',
};
